version: "3.5"

services:
    chat:
        container_name: chat-io
        image: kaiskii/chat-socket-io
        build:
            dockerfile: Dockerfile
            context: .
        ports:
            - 4000:4000/tcp
        env_file: .env
